debug = false

logLevel = "WARN"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
  # [entryPoints.traefik] # Dashboard address
  #   address=":8080"

[retry]

## Prometheus
# [metrics]
#   [metrics.prometheus]
#     entryPoint = "traefik"
#     buckets = [0.1,0.3,1.2,5.0]

[api]
  entrypoint = "traefik"
   dashboard = true

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "example.com" # TODO
  watch = true
  exposedbydefault = false

[acme]
  email = "me@example.com" # TODO: any valid email like gmail.
  storage = "acme.json"
  entryPoint = "https"
  acmeLogging = true
  OnHostRule = true
[acme.httpChallenge]
  entryPoint = "http"
