version: '2'

services:
  shiori:
    image: radhifadlillah/shiori
    restart: always
    container_name: shiori
    networks:
      - traefik
    volumes:
      - $PWD/shiori/data:/srv/shiori
    labels:
      - "traefik.backend=shiori"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:shiori.example.com" # Endpoint name (used by proxy_pass & auto TLS)
      - "traefik.enable=true"
      - "traefik.port=8080" # Application's port (within the container)
      - "traefik.default.protocol=http"

networks:
  traefik:
    external: true
